### ISSUE TITLE
I account an error when I try to run example.py. I am not sure how to solve this

### ISSUE THREAD

**Issue by lmyhappy66** [nikpau/mmgdynamics#3]
Traceback (most recent call last):
  File "E:/MMG_Dynamics/example_test.py", line 1, in <module>
    from mmgdynamics.example import *
  File "<builtin>/frozen zipimport", line 259, in load_module
  File "D:\anaconda3\envs\MMGDynamic\lib\site-packages\mmgdynamics-1.0.6-py3.8.egg\mmgdynamics\example.py", line 6, in <module>
    from mmgdynamics.maneuvers import *
  File "<builtin>/frozen zipimport", line 259, in load_module
  File "D:\anaconda3\envs\MMGDynamic\lib\site-packages\mmgdynamics-1.0.6-py3.8.egg\mmgdynamics\maneuvers.py", line 111, in <module>
    def plot_r(t: list[Sequence[float]]):
TypeError: 'type' object is not subscriptable (key typing.Sequence[float])

Process finished with exit code 1

**Comment by nikpau** [comment]
Hi, and thanks for using my implementation. 

Type hinting for built-in types such as `list[str]` are only valid syntax since Python 3.9. 
Please check if you are using an older version. I will set up a patch for backwards compatibility, so that it works with older versions as well.

**Comment by lmyhappy66** [comment]
I got it. Thanks for your answer very much!
